import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage();
p.on('pageerror', (e) => console.log('PAGEERR', e.message));
p.on('console', (m) => console.log('CONSOLE', m.type(), m.text()));
p.on('requestfailed', (r) => console.log('REQFAIL', r.url()));
await p.goto('http://localhost:4321/organize-pdf');
await p.setInputFiles('[data-input]', '/tmp/claude-0/qa/six.pdf');
await p.waitForTimeout(5000);
console.log(await p.$eval('[data-custom-ui]', (e) => e.innerHTML.slice(0, 300)));
await b.close();
