import { chromium } from '@playwright/test';
const [,, path, out, w = '1280', full = '0', scheme = 'light'] = process.argv;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: +w, height: 900 }, colorScheme: scheme });
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:4321' + path, { waitUntil: 'networkidle' });
await p.screenshot({ path: out, fullPage: full === '1' });
if (errs.length) console.log('ERR', errs);
await b.close();
